HW_1
andrylviv/Andry_Tsupak pull request #1
Opened 2022-01-16 21:20 UTC by andrylviv

2022-01-21 20:42 UTC, KostyantynPanchenko commented
The task itself is completed without any notes. But there are a lot of fixes that should be done. Most of them are related to the code style violations and some to the design. Please fix according to the comments and check ALL classes (not only commented) with regards to the code style and readability.

References:
* Java code conventions - https://www.oracle.com/java/technologies/javase/codeconventions-contents.html
* Google code style (widely used) - https://google.github.io/styleguide/javaguide.html

Please use formatting options of your IDE (`Ctrl + Alt + Shift + o` if you are an Intellij IDEA user)

2022-01-21 21:07 UTC, KostyantynPanchenko commented
Recommendation for commit messages - I would go with the following template HW_{homework_number} - description of what was done.

Simplest example would be:
`HW_1 - implement items 1-5`
`HW_1 - implement items 6-9`
`HW_1 - implement item 10`

More verbose and understandable:
`HW_1 - implement POJO classes and base configuration class`
`HW_1 - provide implementations for Animal interface and extend configuration with PetConfig`
`HW_1 - add more options with Primary and Qualifier annotations`

2022-01-24 18:28 UTC, KostyantynPanchenko requested changes
Please pay attention to missed comments and fix:
* `PetConfig` - please remove extra blank line at the end of the class, only one blank line is required (got two)
* `OtherBeanA` - operators should be separated with a space from both sides. Example: `this.getClass().getSimpleName()+". "+ beanA.getClass().getSimpleName()+ was ...` should be `this.getClass().getSimpleName() + ". " + beanA.getClass().getSimpleName() + was ...`. Please indent properly ALL operators
* `OtherBeanB` - The same as for `OtherBeanA`. Plus there is a wrong message in a `toString()` - it should be `through the setter` instead of `through the constructor`
* `Pet`, line 14 - add space after colon

2022-01-24 19:48 UTC, andrylviv commented on src/main/java/com/epam/spring/homework1/other/OtherBeanA.java
> +    BeanA beanA;
was fixed in "HW_1 - violation fixes" commit

2022-01-24 19:49 UTC, andrylviv commented on src/main/java/com/epam/spring/homework1/other/OtherBeanB.java
> +    BeanB beanB;
was fixed in "HW_1 - violation fixes" commit

2022-01-24 20:57 UTC, KostyantynPanchenko approved these changes

2022-01-24 21:34 UTC, closed without merging